extends: airbnb-base

plugins:
  - import

settings:
  import/core-modules:  ## don't lint for these missing packages in package.json
    - electron  ## 'electron' is only needed as devDependency / global installation

rules:
  # "off" or 0 - turn the rule off
  # "warn" or 1 - turn the rule on as a warning (doesn’t affect exit code)
  # "error" or 2 - turn the rule on as an error (exit code is 1 when triggered)
  indent:
    - error
    - 4  ## number of spaces
  no-console: off  ## allowed for chrome dev-console
  padded-blocks: off
  arrow-body-style: off
  prefer-arrow-callback: off
  no-underscore-dangle: off
  object-curly-spacing: off
  func-names: off
  global-require: off
  class-methods-use-this: off
  comma-dangle:
    - error
    - only-multiline  ## no comma after last item if one line, though allow comma if multiline
  import/no-extraneous-dependencies:  ## checks if required modules are missing in packages.json
    - error
    - devDependencies:  ## declares files, whose imports belong to devDependencies
      - "**/tests/_base.js"
      - "**/*.test.js"
      - "**/gulpTasks/*.js"

globals:  # don't warn about missing declarations
  i18n: true
  mist: true
  beforeEach: true
  LocalStore: true
  web3: true
  Tabs: true
  Tracker: true
  _: true
  window: true
  location: true
  document: true
